docs_dir: 'content'
site_name: 'RBKmoney|docs'
repo_url: https://github.com/rbkmoney/docs
theme: 'material'
strict: true
markdown_extensions:
    - smarty
    - admonition
    - def_list
    - footnotes
    - codehilite
    - toc:
        permalink: True
pages:
    - 'Документация': 'index.md'
    - 'Платформа':
        - 'Терминология': 'platform/glossary.md'
        - 'Быстрый старт': 'platform/overview.md'
    - 'Прием платежей':
        - 'Интерактивный пример': 'integrations/trynow.md'
        - 'Checkout': 'integrations/checkout.md'
        - 'Tokenizer': 'integrations/tokenizer.md'
    - 'Справочники':
        - 'Тестовые карты': 'refs/testcards.md'
    - 'API reference': 'api.md'
